apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  role: "kedify-on-eks-blueprint"
  amiSelectorTerms:
  - alias: "bottlerocket@1.50.0"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "kedify-on-eks-blueprint"
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "kedify-on-eks-blueprint"
  blockDeviceMappings:
  - deviceName: /dev/xvdb
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      deleteOnTermination: true
  tags:
    Name: karpenter-gpu
    intent: inference
